configs {
  key: "onnxchainer.chainerv6"
  value {
    requirement {
      cpu: 4
      disk: 10
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 600
    }
    command: "sh .flexci/run_test.sh"
    environment_variables { key: "PYTHON_VER" value: "37" }
    environment_variables { key: "GPU" value: "0" }
  }
}

configs {
  key: "onnxchainer.win.chainerv6"
  value {
    requirement {
      cpu: 4
      disk: 10
      memory: 16
      gpu: 1
      image: "windows"
    }
    time_limit {
      seconds: 600
    }
    command: ".flexci\\run_test.bat 10.1 37"
  }
}
