configs {
  key: "onnxchainer.chainer-stable"
  value {
    requirement {
      cpu: 4
      disk: 10
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 600
    }
    command: "sh .chainerci/run_test.sh"
    environment_variables {
      key: "PYTHON_VER"
      value: "36"
    }
    environment_variables {
      key: "CHAINER_INSTALL"
      value: ""
    }
  }
}

configs {
  key: "onnxchainer.chainer-pre"
  value {
    requirement {
      cpu: 4
      disk: 10
      memory: 16
      gpu: 1
    }
    time_limit {
      seconds: 600
    }
    command: "sh .chainerci/run_test.sh"
    environment_variables {
      key: "PYTHON_VER"
      value: "36"
    }
    environment_variables {
      key: "CHAINER_INSTALL"
      value: "--pre"
    }
  }
}
